from py_mono.skill.base import Skill, SkillContext
from pathlib import Path

class ScaffoldProjectSkill(Skill):
    def name(self) -> str:
        return "scaffold_project"

    def description(self) -> str:
        return "Create multi-file Python project from workspace/requirements.md"

    def run(self, request: str, context: SkillContext) -> str:
        workspace = context.workspace_root
        req_file = workspace / "requirements.md"
        
        # ADR-018 Gate: requirements.md must exist
        if not req_file.exists():
            return "Missing requirements.md. Run software-design workflow first."
        
        # Read and parse requirements
        read_file = context.agent_tools["read_file"]
        content = read_file.run(path="requirements.md")
        
        # Simple parser - assumes Files: section exists
        files_to_create = []
        in_files_section = False
        for line in content.splitlines():
            if line.strip().startswith("Files:"):
                in_files_section = True
                continue
            if in_files_section:
                if line.strip().startswith("-") and line.strip().endswith(".py"):
                    files_to_create.append(line.strip()[1:].strip())
                elif line.strip() == "" or not line.startswith(" "):
                    in_files_section = False
        
        if not files_to_create:
            return "No Files: section found in requirements.md"
        
        # Create files
        write_file = context.agent_tools["write_file"]
        created = []
        for fname in files_to_create:
            write_file.run(path=fname, content=f"# {fname}\n# Generated by scaffold_project\n")
            created.append(fname)
        
        return f"✅ Scaffolded {len(created)} files: {', '.join(created)}"